### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by t3rminalx** [crazygroot/skillsharedownloader#1]
When I try to grab some courses I get the above error. This is one of the courses it happens with;

https://www.skillshare.com/classes/Boudoir-Portrait-Retouching-for-Photographers/829829877/projects?via=member-home-EnrolledClassesLessonsSection
```

Traceback (most recent call last):
  File "/home/anthony/skillsharedownloader/ss.py", line 11, in <module>
    dl.download_course_by_url(course_url)
  File "/home/anthony/skillsharedownloader/downloader.py", line 36, in download_course_by_url
    self.download_course_by_class_id(m.group(1))
  File "/home/anthony/skillsharedownloader/downloader.py", line 70, in download_course_by_class_id
    for u in data['_embedded']['units']['_embedded']['units']:
TypeError: list indices must be integers or slices, not str

```

**Comment by pka4916** [comment]
i have the same problem.   and it seems that some courses don't have a number as index,  but a letter.   that's why it's failing.
I don't know enough of this,  to make it work,  so hopefully the dev,  till see this
