### ISSUE TITLE
2 issues... help needed.

### ISSUE THREAD

**Issue by pka4916** [crazygroot/skillsharedownloader#2]
I keep having this issue with the files

Traceback (most recent call last):
  File "C:\dl\ss.py", line 11, in <module>
    dl.download_course_by_url(course_url)
  File "C:\dl\downloader.py", line 37, in download_course_by_url
    self.download_course_by_class_id(m.group(1))
  File "C:\dl\downloader.py", line 84, in download_course_by_class_id
    raise Exception('Failed to read video ID from data')
Exception: Failed to read video ID from data

When I use  the only Google tool,  then I get  (after all the downloads)

sending incremental file list
rsync: mkdir "/content/drive/Shareddrives/MEDIA/SS" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(675) [Receiver=3.1.2]

when I try to move it to my Google drive

**Comment by pka4916** [comment]
ok  got it all to work,  i do have another problem.. will post in a seperate one

**Comment by ReneR97** [comment]
hey, 
how did you get it to work?

**Comment by pka4916** [comment]
Never got it to workOn Dec 27, 2022 3:56 PM, Rene Reiterer ***@***.***> wrote:
hey,
how did you get it to work?

**Comment by ReneR97** [comment]
yeah, i managed to fix the "Failed to read video ID from data" error´by removing the "/en/" from the url link, but it just throws another error

**Comment by pka4916** [comment]
The problem is that there are letters in the array, and it can only handle numbers.So if the course is more then 10 files it will fail.1234567890abcde etc..On Dec 28, 2022 3:37 AM, Rene Reiterer ***@***.***> wrote:

yeah, i managed to fix the "Failed to read video ID from data" error´by removing the "/en/" from the url link, but it just throws another error

**Comment by ReneR97** [comment]
hey, if you still need a script to download a full course from skillshare, i made one that works. 
Since i dont know phython that well its made in nodejs. 
You can have a look here: https://github.com/ReneR97/skillshare-downloader

**Comment by pka4916** [comment]
Oh awesome, let me check it out.Thank you.On Dec 29, 2022 6:41 AM, Rene Reiterer ***@***.***> wrote:
hey, if you still need a script to download a full course from skillshare, i made one that works.
Since i dont know phython that well its made in nodejs.
You can have a look here: https://github.com/ReneR97/skillshare-downloader

**Comment by 2512821228** [comment]
> hey, if you still need a script to download a full course from skillshare, i made one that works. Since i dont know phython that well its made in nodejs. You can have a look here: https://github.com/ReneR97/skillshare-downloader

Thank you for your work!
